# -*- coding: utf-8 -*-

import unittest
from src.testcase.test_albumplay import test_albumplay_case
from HTMLTestRunner_Chart import HTMLTestRunner
import time

'''单独执行某些Case'''
suite = unittest.TestSuite()
testcase1 = [test_albumplay_case("test10_order")]
suite.addTests(testcase1)

 # '''执行单一文件下的所有Case'''
# suite=unittest.TestSuite()
# suite.addTests(unittest.TestLoader().loadTestsFromTestCase(test_albumplay_case))


# '''执行目录下的所有case'''
# path='./src/testcase/'
# suite=unittest.defaultTestLoader.discover(path,pattern="test_*.py")

'''生成测试报告'''
if __name__=="__main__":
    now = time.strftime("%Y-%m-%d %H_%M_%S")
    filename = './report/' + now + '_result.html'
    with open(filename, 'wb') as f:
        runner = HTMLTestRunner(stream=f,
                                title=u'云听 android Test Report',
                                description='generated by HTMLTestRunner.',
                                retry=2,
                                verbosity=2
                                )
        run=HTMLTestRunner()
        runner.run(suite)
